name: Auto PR and Merge

on:
  push:
    branches:
      - '*'  # This triggers the workflow for pushes to any branch

permissions:
  pull-requests: write  # Ensures the token can create and merge pull requests

jobs:
  auto-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Git commit data
      uses: rlespinasse/git-commit-data-action@v1.x

    - name: Raise PR
      uses: peter-evans/create-pull-request@v3
      with:
        branch: "auto-pr-branch"
        title: "Auto PR for changes"
        commit-message: "Automated changes from the auto-pr-branch"
        body: "This PR was automatically created by GitHub Actions."
        author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>

    - name: Merge PR
      if: steps.create_pr.outputs.pull-request-url != ''
      run: |
        PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oP '\d+$')
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
          -d '{"merge_method":"merge"}'
