name: Auto PR and Merge

on:
  push:
    branches:
      - '*'  # Trigger on push to any branch

jobs:
  auto-pr-and-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Verify if Git is initialized
    - name: Verify if Git is initialized
      run: git rev-parse --is-inside-work-tree

    # Show Git status (includes information on uncommitted changes)
    - name: Show Git status
      run: git status

    # Show recent commits (to confirm correct commit history)
    - name: Show recent commits
      run: git log --oneline -n 5

    # Validate that the working directory is clean
    - name: Validate the working directory is clean
      run: |
        git diff --exit-code || echo "There are uncommitted changes."

    # Create a Pull Request
    - name: Create a Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        branch: ${{ github.head_ref }}  # Use the current branch
        title: "Auto PR for changes"
        commit-message: "Automated changes from ${{ github.head_ref }}"
        body: "This PR was automatically created by GitHub Actions."
        base: main  # Merge into the main branch

    # Output the PR URL
    - name: Check PR URL
      run: |
        echo "PR URL: ${{ steps.create_pr.outputs.pull-request-url }}"

    # Merge Pull Request (if PR was created)
    - name: Merge Pull Request
      if: steps.create_pr.outputs.pull-request-url != ''
      run: |
        PR_NUMBER=$(echo "${{ steps.create_pr.outputs.pull-request-url }}" | grep -oP '\d+$')
        curl -X PUT \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/merge \
          -d '{"merge_method":"merge"}'
